const upcomingIpodata = [
  {
    currentPrice: null,
    filedDate: "2023-11-08",
    firstDayClose: null,
    status: "WEEK OF",
    companyName: "HW ELECTRO CO., LTD.",
    lockupPeriod: "",
    managers: "UNIVEST SECURITIES",
    offeringDate: "2024-01-08",
    offerPrice: null,
    priceRangeHigh: 4,
    priceRangeLow: 4,
    quietperiod: "",
    return: null,
    shares: 3750000,
    symbol: "HWEP",
    updated: "2024-01-02",
    volume: 15000000,
  },
  {
    currentPrice: null,
    filedDate: "2023-10-19",
    firstDayClose: null,
    status: "WEEK OF",
    companyName: "J-LONG GROUP LIMITED",
    lockupPeriod: "",
    managers: "EDDID SECURITIES USA",
    offeringDate: "2024-01-08",
    offerPrice: null,
    priceRangeHigh: 6,
    priceRangeLow: 4,
    quietperiod: "",
    return: null,
    shares: 1400000,
    symbol: "JL",
    updated: "2024-01-04",
    volume: 7000000,
  },
  {
    currentPrice: null,
    filedDate: "2023-09-06",
    firstDayClose: null,
    status: "THURSDAY",
    companyName: "SMITH DOUGLAS HOMES CORP.",
    lockupPeriod: "",
    managers:
      "J.P. MORGAN/ BOFA SECURITIES/ RBC CAPITAL MARKETS/WELLS FARGO SECURITIES/WOLFE | NOMURA ALLIANCE/ ZELMAN PARTNERS",
    offeringDate: "2024-01-11",
    offerPrice: null,
    priceRangeHigh: 21,
    priceRangeLow: 18,
    quietperiod: "",
    return: null,
    shares: 7690000,
    symbol: "SDHC",
    updated: "2024-01-05",
    volume: 150000000,
  },
  {
    currentPrice: null,
    filedDate: "2023-12-19",
    firstDayClose: null,
    status: "FRIDAY",
    companyName: "SILYNXCOM LTD.",
    lockupPeriod: "",
    managers: "THINKEQUITY",
    offeringDate: "2024-01-12",
    offerPrice: null,
    priceRangeHigh: 6,
    priceRangeLow: 4,
    quietperiod: "",
    return: null,
    shares: 1080000,
    symbol: "SYNX",
    updated: "2024-01-03",
    volume: 5380000,
  },
  {
    currentPrice: null,
    filedDate: "2023-11-08",
    firstDayClose: null,
    status: "WEDNESDAY",
    companyName: "HW ELECTRO CO., LTD.",
    lockupPeriod: "",
    managers: "UNIVEST SECURITIES",
    offeringDate: "2024-01-17",
    offerPrice: null,
    priceRangeHigh: 4,
    priceRangeLow: 4,
    quietperiod: "",
    return: null,
    shares: 3750000,
    symbol: "HWEP",
    updated: "2024-01-04",
    volume: 15000000,
  },
  {
    currentPrice: null,
    filedDate: "2023-10-10",
    firstDayClose: null,
    status: "THURSDAY",
    companyName: "PERFECT MOMENT LTD.",
    lockupPeriod: "",
    managers: "THINK EQUITY/ LAIDLAW &AMP; CO. (UK)",
    offeringDate: "2024-01-25",
    offerPrice: null,
    priceRangeHigh: 7,
    priceRangeLow: 6,
    quietperiod: "",
    return: null,
    shares: 2500000,
    symbol: "PMNT",
    updated: "2024-01-03",
    volume: 16250000,
  },
];
export default upcomingIpodata;
